name: CI to VS Marketplace
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1.0.7
        with:
          pat: ${{ secrets.VS_ACCESS_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com